public class CollectionsClass {
    public String str = 'jkfbgfkjfgkjfbg 8';
    Integer inte = 688976;
    Boolean boolVar = false;
    Account accVar = new Account();
    
    Public void collectionsMethod() {   
    	accVar.Name = 'Simran';
    	accVar.Active__c = 'Yes';
        
        //do it for conatct and oppo
    }
    
    public void listMethods()
    {
    }
    
     public void setMethods()
    {
    }
    
     public void mapMethods()
    {
    }
}